### ISSUE TITLE
Peer Discovery & NAT traversal

### ISSUE THREAD

**Issue by JLauriks** [key-party/CS4160-trustchain-android#1]
Added the TomP2P Library not sure if this will work but the examples seem promising

https://github.com/tomp2p/TomP2P/blob/master/examples/src/main/java/net/tomp2p/examples/ExampleNATChat.java

Leaving this here for future referencing

**Comment by bas921** [comment]
(discussed internally, but for the record)

There's currently an upstream pull request that enables peer discovery at https://github.com/wkmeijer/CS4160-trustchain-android/pull/59 .

Anticipating this pull request I've merged our master with the other fork master to try out if this is a solution for us. There are some issues, but it could work.

When the upstream pull request gets accepted we can merge and cherry pick the commits that build on top of this, or worst case manually port code to the newer version.

**Comment by JLauriks** [comment]
The merged pull request (https://github.com/wkmeijer/CS4160-trustchain-android/pull/59) only discovers other peers. It sends the IP and Port number to the TrustChainActivity. 

TrustChainActivity is only listening on port 8080 so it will not work with the port that has been punched by the App2App communication activity (OverviewConnectionsActivity).

Also note that in connection.network.ClientTask a socket is opened on NetworkCommunication.DEFAULT_PORT and never on the port assigned when creating the task

**Comment by bas921** [comment]
App2App communication has been fully implemented since 4cdbca63200d3381daafb7e72acc6e042f9896d8 by @JLauriks .
