### ISSUE TITLE
Keyshare Exchange Protocol

### ISSUE THREAD

**Issue by bas921** [key-party/CS4160-trustchain-android#3]
To securely transfer shares, the shares are encrypted by a one-time session key generated by a ECDH key exchange (implemented in #2). This issue describes the off-chain communication protocol used by point 2 and 3 in more detail.

For now, on a high level the following occurs when successfully initiating a keyshare exchange. **A** initiates a keyshare exchange with trustee **B**:
1. **A** generates a temporary ECDH session keypair
2. **A** sends his public session key to **B** together with a keyshare exchange request and a (ECDSA) signature of the key
3. **B** verifies that the public session key indeed belongs to known peer **A** by validating the signature
4. **B** generates his own ECDH session keypair
5. In the same fashion, **B** sends his public session key to **A** with a (ECDSA) signature of the key
6. After verification by **A** that the session key is indeed from known peer **B**, both **A** and **B** now have the same shared secret
7. **A** encrypts the keyshare + prime using AES-GCM and the shared secret
8. **A** can send the encrypted data directly to **B** after which final on-chain verification happens through the Trustchain (described in #2)
9. The session keypair is discarded

The messages will be defined in a to be determined protobuf format, similar to the crawl and half block messages.
How the keyshare is securely stored by the trustee has yet to be determined.

Requirements for initiating a keyshare exchange are:
- Both participants are ready for an interactive session
- The trustee is already known as a peer by the sender
- The sender is already known as a peer by the trustee

**Comment by JLauriks** [comment]
I would suggest to divide this into 3 Protobuf messages:

- request_keyshare
 For steps 1 and 2

- request_keyshare_response
 The response of B for steps 3, 4 and 5

- keyshare
 The actual exchange of the keyshares (as described in steps 6, 7 and 8)

- keyshare_respone (optional)
 This is not described in the protocol above, in this response B could reply to A that the exchange happend correctly or an error message if anything went wrong.

**Comment by marius-pop0** [comment]
Issue has been resolved including on-chain verification

**Comment by bas921** [comment]
Session integration since 3c693161d418578857f760f47a2d9aa8c55526bb and on-chain verification since 9efef76a2c54a4c091d52f97af504b534bd2a5fb.
