### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by jeffsirocki** [key-party/CS4160-trustchain-android#9]
link to edit:
https://drive.google.com/file/d/1DJbbp66SoTAKb2dYIJYuY9OaA4LAwMTX/view?usp=sharing

**Comment by JLauriks** [comment]
@jeffsirocki The designs are mainly for keyshares right?

How would the interaction of the actual sending to a Peer work?

**Comment by jeffsirocki** [comment]
Yes, so far just mocked up for splitting and sending keyshares, and key recovery and sending keyshares for recovery.

For sending to a Peer, we may need an update, we would like a screen that lists nearby peers correct? We want to locate and connect to nearby peers for all interaction?

**Comment by JLauriks** [comment]
If you take a look at the App with the AppToApp communication they have a list of detected peers on the P2P network. Maybe we could use something like this?

![Screenshot](https://user-images.githubusercontent.com/325224/33896945-77dccf72-df64-11e7-9d9c-fdda012216ac.png)

**Comment by jeffsirocki** [comment]
Yes, this is great, exactly what we should bring into our app for peer interaction. How does the list populate the name of the connected device?

**Comment by JLauriks** [comment]
They do this via the PeerAdapterList, the code for that list is already in the master branch
